import { Inter, Outfit, Urbanist } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import "bootstrap-icons/font/bootstrap-icons.css"
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin']
});
const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ['latin']
})
const urbanist = Urbanist({
  variable: '--font-urb',
  subsets: ['latin']
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${inter.variable} ${urbanist.variable}`}>{children}</body>
    </html>
  );
}
